/*
FUNÇÕES DE CONVERSÃO DE VALORES
PODE SER UTILIZADA QUANDO NECESSÁRIO A CONVERSÃO DE UM VALOR PARA EFETUAR OPERAÇÕES MATEMÁTICAS OU CONCATENAÇÃO
É NECESSÁRIO LEMBRAR QUE: O SQL AUTOMATICAMENTE CONVERTE UMA STRING PARA UM CARACTERE NUMÉRICO, MAS NUNCA O CONTRÁRIO
POR EXEMPLO: 
	SELECT '1' + 1;
	RETORNARÁ O VALOR 2, POIS O 1 EM STRING FOI CONVERTIDO PARA INT.
	
	SELECT '1' + '1';
	NESTE CASO, AMBOS PARÂMETROS ESTÃO EM STRING, O QUE SUGERE QUE SEJA FEITA UMA CONCATENAÇÃO DE STRINGS, RESULTANDO EM 11.

PARA CONVERSÃO DE VALORES, TEMOS A FUNÇÃO CAST(). ESTA FUNÇÃO NECESSITA DE DOIS PARÂMETROS PARA FUNCIONAR. 
POR EXEMPLO:
	SELECT CAST(['VALOR'/'1'] AS [INT/STRING/FLOAT/...]) + CAST(['VALOR'/'1'] AS [INT/STRING/FLOAT/...])
*/
SELECT CAST('1' AS INT) + CAST ('1' AS INT)
