/*
TEMOS A FUNÇÃO CHARINDEX, QUE EXIBE O INDICE NO QUAL A BUSCA ESTÁ SENDO FEITA PELO PARÂMETRO PASSADO
POR EXEMPLO:
	SELECT CHARINDEX(['TEXTOPARABUSCA'], [COLUNAPARABUSCA], [INICIODABUSCA(QUAL POSIÇÃO COMEÇAR A BUSCAR. OPCIONAL)])
	O PRIMEIRO CAMPO SELECIONA QUAL O TEXTO QUE SERÁ BUSCADO, A COLUNA PARA BUSCA, E POR ÚLTIMO SERÁ VERIFICADO A PARTIR DE QUAL CAMPO SERÁ FEITA A BUSCA. POR EXEMPLO, SE SELECIONADO 2, SERÁ FEITA A BUSCA A PARTIR DO SEGUNDO CARACTERE DA PALAVRA AVALIADA. CASO SEJA VITOR, SELECIONANDO POR BUSCA DA LETRA I E SENDO VERIFICADO A PARTIR DO CAMPO 2, SERÁ ENCONTRADO NO CAMPO 2. MESMO SENDO INICIADA A BUSCA PELO SEGUNDO CAMPO, ELE NÃO DESCONSIDERARÁ ESTE CAMPO NO RESULTADO, SOMENTE NA BUSCA.
*/
SELECT NOME, CHARINDEX('A', NOME) FROM ALUNO
