--FUNÇÃO GETDATE() PARA SELECIONAR O DATA ATUAL
SELECT GETDATE() AS DIAHORAATUAL

/*
PARA O DATEDIFF É NECESSÁRIO ATRIBUIR 3 PARÂMETROS PARA A FUNÇÃO. O PRIMEIRO PARÂMETRO SELECIONA O FORMATO QUE SERÁ CALCULADA A DIFERENÇA (INTERVALO), O SEGUNDO O PARÂMETRO DE INICIO E POR ÚLTIMO O PARÂMETRO DE FINAL.
POR EXEMPLO: 
	SELECT DATADIFF([DAY/MONTH/YEAR/HOUR/MINUTE], [DATAINICIAL], [DATAFINAL]) FROM TABELA
*/
SELECT NOME, DATEDIFF(YEAR, NASCIMENTO, GETDATE()) AS IDADE FROM ALUNO

/*
A FUNÇÃO DATENAME() RETORNA O NOME DA DATA, MAIS ESPECIFICAMENTE O CAMPO SELECIONADO. 
POR EXEMPLO:
	SELECT DATENAME([YEAR/MONTH/DAY/WEEKDAY], [DATA/REGISTRO_DA_TABELA_COM_DATA]) AS NOMEDATA FROM TABELA
	POR TRAZER O NOME, ELE RETORNA A RESPOSTA EM FORMATO DE >>>> STRING <<<<
*/
SELECT NOME, DATENAME(WEEKDAY, NASCIMENTO) AS DATA FROM ALUNO

/*
A FUNÇÃO DATEPART() FAZ O MESMO QUE A DATENAME() COM SOMENTE A DIFERENÇA DE QUE UMA RETORNA A RESPOSTA EM FORMATO DE STRING E A OUTRA EM FORMATO INTEIRO.
PODE SE OBSERVAR ISSO, UTILIZANDO O PARÂMTRO WEEKDAY, ONDE ELA RETORNARÁ AO INVÉS DE 'SEGUNDA' OU 'TERÇA', RETORNARÁ '2', '3' PORÉM INDICANDO A MESMA RESPOSTA SOMENTE EM FORMATO DIFERENTE.
*/
SELECT NOME, DATEPART(YEAR, NASCIMENTO) AS DATA FROM ALUNO

/*
A FUNÇÃO DATEADD() SOMA A DATA SELECIONADA COM OS PARÂMETROS SOLICITADOS.
POR EXEMPLO: 
	SELECT DATEADD([DAY/MONTH/YEAR/HOUR/MINUTE/SECOND], [INCREMENTO(REFERENTE AO PARÂMETRO ANTERIOR)], [DATA_PARA_INCREMENTAR_OS_PARÂMETROS])
*/
SELECT NOME, DATEADD(SECOND, 365, GETDATE()) FROM ALUNO
