--UMA ESTRUTURA IF ELSE SIMPLES

BEGIN
IF 
		'VITORIA BEATRIIZ' IN (
								SELECT 
									A1_NOME 
								FROM 
									SA1020 
								WHERE 
									A1_NOME LIKE '%VITOR%'
							)
		PRINT 'ENCONTRADO'
ELSE 
		PRINT 'NOTTODAYSATAN'
END

/*A INSTRUÇÃO IF FUNCIONA COMO EM QUALQUER OUTRA LINGUAGEM
O COMANDO DEVE SER INICIANDO COM BEGIN E ENCERRADO COM END
SUA ESTRUTURA FICARÁ ASSIM: 
BEGIN
	IF  
END
GO
*/


--ABAIXO É POSSÍVEL VER UMA ESTRUTURA IF ELSE COM CRIAÇÃO DE VARIÁVEIS, COMPARAÇÃO DE VALORES QUE SÃO RESULTADOS DE SUB-QUERIES
DECLARE 
	@PRODUTO VARCHAR (50) = 'FV2300001C5666',
	@NOTA VARCHAR (10) = '000005699'


BEGIN

IF (
	SELECT 
		TOP 1 B6_PRODUTO 
	FROM 
		SB6020 
	WHERE 
		@PRODUTO = B6_PRODUTO 
		AND @NOTA = B6_DOC
	) = (
	SELECT 
		TOP 1 C6_PRODUTO 
	FROM 
		SC6020 
	WHERE 
		C6_PRODUTO = @PRODUTO
	) 
	PRINT
		'ENCONTRADO'
ELSE
	PRINT 
		'DOESNT EXISTS'
END 
