--FUNÇÃO ISNULL PARA VERIFICAÇÃO DO CAMPO. CASO SEJA NULO, RETORNARÁ O VALOR EM ASPAS. 
SELECT NOME, 
	     ISNULL(TIPO, '***') AS TIPO,
	     ISNULL(NUMERO, 'SEM NUM') AS NUMERO,
	     BAIRRO, 
	     UF
FROM ALUNO AS A
LEFT JOIN ENDERECO AS E
ON E.ID_ALUNO = A.IDALUNO
LEFT JOIN TELEFONE AS T
ON T.ID_ALUNO = A.IDALUNO
