--PROCEDURE COM QUERY DE RELATÓRIO
--PROCEDURE FUNCIONA COMO UMA FUNCTION QUE PODE OU NÃO CONTER UMA SEQUÊNCIA DE COMANDOS OU QUERIES.
CREATE OR ALTER PROCEDURE CONSULTA
AS
BEGIN
	SELECT TOP 10 R.A3_NOME AS REPRESENTANTE, C5_NUM AS PEDIDO, C6_QTDVEN AS QUANTIDADE, C5_NOTA AS NF
	FROM SA3020 AS R
		INNER JOIN SC5020 AS P
	ON R.A3_COD = P.C5_VEND1 AND P.D_E_L_E_T_ = ' '
		INNER JOIN SC6020 AS Q
	ON C5_NUM = C6_NUM AND Q.D_E_L_E_T_ = ' '
	WHERE C5_EMISSAO BETWEEN '20230801' AND '20230831' AND R.D_E_L_E_T_ = ' ' 
END 

--COMANDO PARA EXECUTAR A PROCEDURE (EXEC NOMEDAPROCEDURE)
EXEC CONSULTA

-- COMANDO PARA EXCLUIR A PROCEDURE (DROP PROCEDURE NOMEDAPROCEDURE)
DROP PROCEDURE CONSULTA
	
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

--PROCEDURE SIMPLES COM PARÂMETROS
CREATE PROCEDURE CONTA (@NUMERO1 INT, @NUMERO2 INT)
AS
BEGIN
	SELECT @NUMERO1 + @NUMERO2 AS CONTA
END
	
--COMANDO PARA EXECUTAR PROCEDURE. NÃO É NECESSÁRIO OS PARÊNTESES () PARA CHAMAR OS PARÂMETROS
EXEC CONTA 10, 20

|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

--EXERCÍCIOS

--CRIA A BASE DE DADOS DO PROJETO
CREATE DATABASE PROJETO
--ACESSA A BASE DE DADOS ESPECIFICADA
USE PROJETO

--CRIA A TABELA DE CURSOS
CREATE TABLE CURSOS(
	IDCURSO INT IDENTITY (1, 1) PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT NOT NULL,
	VALOR FLOAT NOT NULL
);

--ALIMENTA A TABELA
INSERT INTO CURSOS VALUES ('JAVA', 36, 99.99)
INSERT INTO CURSOS VALUES ('FUNDAMENTOS DE BANCO DE DADOS', 360, 500.00)

--PROCEDURE PARA CADASTRAR CURSO NA TABELA CURSOS
CREATE OR ALTER PROCEDURE CAD_CURSO
	(@NOME VARCHAR (30) , 
	 @HORAS INT, 
	 @VALOR FLOAT)
AS 
BEGIN
	INSERT INTO CURSOS VALUES (@NOME, @HORAS, @VALOR)
END
	
--CRIAR UMA PROCEDURE PARA CONSULTAR CURSOS
CREATE OR ALTER PROCEDURE CONSULTACURSO (@NOME VARCHAR(30))
AS
BEGIN
	SELECT @NOME, HORAS, VALOR FROM CURSOS
	WHERE NOME = @NOME
END

--COMANDO PARA EFETUAR A CONSULTA DO CURSO ESPECIFICO PASSANDO O PARÂMETRO
EXEC CONSULTACURSO 'LINUX'
