--PROCEDURE COM QUERY DE RELATÓRIO
--PROCEDURE FUNCIONA COMO UMA FUNCTION QUE PODE OU NÃO CONTER UMA SEQUÊNCIA DE COMANDOS OU QUERIES.
CREATE OR ALTER PROCEDURE CONSULTA
AS
BEGIN
	SELECT TOP 10 R.A3_NOME AS REPRESENTANTE, C5_NUM AS PEDIDO, C6_QTDVEN AS QUANTIDADE, C5_NOTA AS NF
	FROM SA3020 AS R
		INNER JOIN SC5020 AS P
	ON R.A3_COD = P.C5_VEND1 AND P.D_E_L_E_T_ = ' '
		INNER JOIN SC6020 AS Q
	ON C5_NUM = C6_NUM AND Q.D_E_L_E_T_ = ' '
	WHERE C5_EMISSAO BETWEEN '20230801' AND '20230831' AND R.D_E_L_E_T_ = ' ' 
END 

--COMANDO PARA EXECUTAR A PROCEDURE (EXEC NOMEDAPROCEDURE)
EXEC CONSULTA

-- COMANDO PARA EXCLUIR A PROCEDURE (DROP PROCEDURE NOMEDAPROCEDURE)
DROP PROCEDURE CONSULTA
